### ISSUE TITLE
小黑子

### ISSUE THREAD

**Issue by TuShanShengYao** [zzp198/SSC#1]
你干嘛~诶呦。
哇，真的是你呀~
你咋换头像啦？
哈哈哈哈哈哈哈
![psc](https://user-images.githubusercontent.com/118150137/231774580-f08f8475-c1f4-469a-959e-f80d89321657.jpg)

**Comment by zzp198** [comment]
不是同一个号，上一个号刚刚弃用了，这个是新的，注意id是zzp198还是zzp198-old

**Comment by TuShanShengYao** [comment]
哈哈哈哈哈哈，我还以为这个GitHub的账号不用了呢 哈哈哈哈。加好友吗？2431247501
微信：TuShanShengYao

**Comment by TuShanShengYao** [comment]
晚安啦
