### ISSUE TITLE
救救非steam用户吧

### ISSUE THREAD

**Issue by gsf114514** [zzp198/SSC#3]
![image](https://github.com/zzp198/SSC/assets/132669717/84e96514-b98d-42e2-81e6-543467b64585)
因为这个获取steamID，导致G(白)O(嫖)G用户无法使用这个mod

**Comment by zzp198** [comment]
不使用steamid的话，那就只能用户名密码的形式，也不是不行，会麻烦很多。等下个版本更新吧。

而且白嫖用户建议买正版支持下，真的就是一顿饭钱的事。
